server:
  port: 9005
spring:
  profiles:
    active: dev
  application:
    name: vote-system-demo
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

static-res:
  port: 9006

server-ip: 121.196.145.171
