server:
  port: 9005
spring:
  profiles:
    active: dev
  application:
    name: vote-system-demo
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

static-res:
  suffix: res

server-ip: 121.196.145.171
#server-ip: 82.156.199.7

alibaba:
  face:
    access-key-id: LTAI4G2g7tsypRyNFCYGVNuz
    access-key-secret: uhUqUntAC23ENC2dRm0CavtNCkrPCK
    region-id: cn-shanghai
    bucket-name: face-test-mango-shanghai
    access-url: face-test-mango-shanghai.oss-cn-shanghai.aliyuncs.com
    endpoint: http://oss-cn-shanghai.aliyuncs.com
    default-db-name: default

face-verify:
  #小程序人脸识别模块是否展示
  is-show: false


#logging:
#  config: classpath:logback.xml
#  level:
#    com.mapper: debug
#    com.pojo.mapper: debug