spring:
  datasource:
    url: jdbc:mysql://121.196.145.171:3307/property_manage?tinyInt1isBit=false&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: demo
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis-plus:
  configuration:
    # 标准输出形式
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 启用驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations:
    - classpath:mapperxml/*.xml
    - classpath:com/pojo/mapperxml/*.xml
  type-aliases-package:
    - com.domain
    - com.pojo

file:
  root: /res/${spring.application.name}
  avatar: ${file.root}/avatar/
  tmp: ${file.root}/tmp/
  document: ${file.root}/document/